export type BookType = 'textbook' | 'guide' | 'solution' | 'other';

export interface Book {
  id: string;
  title: string;
  slug: string;
  class_name: string;
  class_slug: string;
  subject: string;
  subject_slug: string;
  book_type: BookType;
  year: number;
  description: string;
  cover_image: string;
  pdf_url: string;
  file_size?: string;
  author?: string;
  publisher?: string;
  is_published: boolean;
  is_latest?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface ClassCategory {
  name: string;
  slug: string;
  bnName: string;
  count?: number;
}

export interface SubjectCategory {
  name: string;
  slug: string;
  bnName: string;
}

export const CLASSES_LIST: ClassCategory[] = [
  { name: 'Class 1', slug: 'class-1', bnName: 'প্রথম শ্রেণি' },
  { name: 'Class 2', slug: 'class-2', bnName: 'দ্বিতীয় শ্রেণি' },
  { name: 'Class 3', slug: 'class-3', bnName: 'তৃতীয় শ্রেণি' },
  { name: 'Class 4', slug: 'class-4', bnName: 'চতুর্থ শ্রেণি' },
  { name: 'Class 5', slug: 'class-5', bnName: 'পঞ্চম শ্রেণি' },
  { name: 'Class 6', slug: 'class-6', bnName: 'ষষ্ঠ শ্রেণি' },
  { name: 'Class 7', slug: 'class-7', bnName: 'সপ্তম শ্রেণি' },
  { name: 'Class 8', slug: 'class-8', bnName: 'অষ্টম শ্রেণি' },
  { name: 'Class 9-10', slug: 'class-9-10', bnName: 'নবম-দশম শ্রেণি' },
  { name: 'SSC', slug: 'ssc', bnName: 'এসএসসি' },
  { name: 'HSC', slug: 'hsc', bnName: 'এইচএসসি' },
  { name: 'Admission', slug: 'admission', bnName: 'বিশ্ববিদ্যালয় ভর্তি পরীক্ষা' },
  { name: 'College Admission', slug: 'college-admission', bnName: 'একাদশ শ্রেণি ও কলেজ ভর্তি' },
];

export const SUBJECTS_LIST: SubjectCategory[] = [
  { name: 'Bangla', slug: 'bangla', bnName: 'বাংলা' },
  { name: 'English', slug: 'english', bnName: 'ইংরেজি' },
  { name: 'Mathematics', slug: 'math', bnName: 'গণিত' },
  { name: 'Science', slug: 'science', bnName: 'বিজ্ঞান' },
  { name: 'ICT', slug: 'ict', bnName: 'তথ্য ও যোগাযোগ প্রযুক্তি' },
  { name: 'BGS (Bangladesh & Global Studies)', slug: 'bgs', bnName: 'বাংলাদেশ ও বিশ্বপরিচয়' },
  { name: 'Islam Studies', slug: 'islamic-studies', bnName: 'ইসলাম ও নৈতিক শিক্ষা' },
  { name: 'Hindu Studies', slug: 'hindu-studies', bnName: 'হিন্দুধর্ম ও নৈতিক শিক্ষা' },
  { name: 'Agriculture', slug: 'agriculture', bnName: 'কৃষি শিক্ষা' },
  { name: 'Physics', slug: 'physics', bnName: 'পদার্থবিজ্ঞান' },
  { name: 'Chemistry', slug: 'chemistry', bnName: 'রসায়ন' },
  { name: 'Biology', slug: 'biology', bnName: 'জীববিজ্ঞান' },
  { name: 'Higher Mathematics', slug: 'higher-math', bnName: 'উচ্চতর গণিত' },
  { name: 'Accounting', slug: 'accounting', bnName: 'হিসাববিজ্ঞান' },
  // University Admission Categories
  { name: 'DU (Dhaka University)', slug: 'du', bnName: 'ঢাকা বিশ্ববিদ্যালয় (DU)' },
  { name: 'BUET & Engineering', slug: 'buet', bnName: 'বুয়েট ও প্রকৌশল (BUET)' },
  { name: 'CU (Chittagong University)', slug: 'cu', bnName: 'চট্টগ্রাম বিশ্ববিদ্যালয় (CU)' },
  { name: 'RU (Rajshahi University)', slug: 'ru', bnName: 'রাজশাহী বিশ্ববিদ্যালয় (RU)' },
  { name: 'Medical & Dental', slug: 'medical', bnName: 'মেডিকেল ও ডেন্টাল (Medical)' },
  { name: 'GST General Varsity', slug: 'gst', bnName: 'গুচ্ছ বিশ্ববিদ্যালয় (GST)' },
  { name: 'Agri Varsity GST', slug: 'agri', bnName: 'কৃষি গুচ্ছ (Agri GST)' },
];

// College Admission Types & Constants
export interface CollegeReqItem {
  collegeName: string;
  slug?: string;
  location: string;
  shift?: string;
  type?: string;
  scienceGPA: string;
  commerceGPA: string;
  artsGPA: string;
  seats: string;
  image?: string;
}

export interface DivisionRequirement {
  division: string;
  slug: string;
  bnName: string;
  colleges: CollegeReqItem[];
}

export const TOP_DHAKA_COLLEGES_REQ: CollegeReqItem[] = [
  { collegeName: 'নটর ডেম কলেজ (Notre Dame College)', slug: 'ndc', location: 'মতিঝিল, ঢাকা', shift: 'দিবা (ছাত্র)', type: 'নিজস্ব পরীক্ষা', scienceGPA: '5.00 (Math & Physics GPA 5.00)', commerceGPA: '4.50', artsGPA: '3.50', seats: '৩,২০০+' },
  { collegeName: 'হলিক্রস কলেজ (Holy Cross College)', slug: 'holy-cross', location: 'ফার্মগেট, ঢাকা', shift: 'দিবা (ছাত্রী)', type: 'নিজস্ব পরীক্ষা', scienceGPA: '5.00', commerceGPA: '4.00', artsGPA: '3.00', seats: '২,১০০+' },
  { collegeName: 'সেন্ট জোসেফ উচ্চ মাধ্যমিক বিদ্যালয় (St. Joseph)', slug: 'st-joseph', location: 'মোহাম্মদপুর, ঢাকা', shift: 'দিবা (ছাত্র)', type: 'নিজস্ব পরীক্ষা', scienceGPA: '5.00', commerceGPA: '4.00', artsGPA: '3.50', seats: '৯০০+' },
  { collegeName: 'ঢাকা কলেজ (Dhaka College)', slug: 'dhaka-college', location: 'নিউ মার্কেট, ঢাকা', shift: 'দিবা (ছাত্র)', type: 'সরকারি', scienceGPA: '5.00 (Total Marks 1150+)', commerceGPA: '4.75', artsGPA: '4.25', seats: '১,২০০+' },
  { collegeName: 'ভিকারুননিসা নূন স্কুল অ্যান্ড কলেজ', slug: 'viqarunnisa-noon', location: 'বেইলি রোড, ঢাকা', shift: 'প্রভাতী ও দিবা (ছাত্রী)', type: 'বেসরকারি স্বনামধন্য', scienceGPA: '5.00 (Total Marks 1140+)', commerceGPA: '4.75', artsGPA: '4.25', seats: '২,০০০+' },
  { collegeName: 'আইডিয়াল স্কুল অ্যান্ড কলেজ', slug: 'ideal-motijheel', location: 'মতিঝিল, ঢাকা', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'বেসরকারি স্বনামধন্য', scienceGPA: '5.00 (Total Marks 1135+)', commerceGPA: '4.75', artsGPA: '4.00', seats: '১,৫০০+' },
  { collegeName: 'রাজউক উত্তরা মডেল কলেজ', slug: 'rajuk-uttara-model', location: 'উত্তরা, ঢাকা', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'সরকারি ট্রাস্ট', scienceGPA: '5.00 (Total Marks 1160+)', commerceGPA: '4.85', artsGPA: '4.50', seats: '১,১০০+' },
  { collegeName: 'আদমজী ক্যান্টনমেন্ট কলেজ', slug: 'adamjee-cantonment', location: 'ঢাকা ক্যান্টনমেন্ট', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'সেনাবাহিনী পরিচালিত', scienceGPA: '5.00 (Total Marks 1130+)', commerceGPA: '4.75', artsGPA: '4.25', seats: '১,৮০০+' },
  { collegeName: 'সরকারি বিজ্ঞান কলেজ (Government Science College)', slug: 'government-science-college', location: 'ফার্মগেট, ঢাকা', shift: 'দিবা (ছাত্র)', type: 'সরকারি বিশেষায়িত', scienceGPA: '5.00 (Total Marks 1120+)', commerceGPA: 'N/A', artsGPA: 'N/A', seats: '১,২০০' },
  { collegeName: 'ঢাকা রেসিডেনসিয়াল মডেল কলেজ', slug: 'residential-model', location: 'মোহাম্মদপুর, ঢাকা', shift: 'প্রভাতী ও দিবা (ছাত্র)', type: 'সরকারি ট্রাস্ট', scienceGPA: '5.00 (Total Marks 1145+)', commerceGPA: '4.50', artsGPA: '4.00', seats: '১,০০০+' },
  { collegeName: 'ঢাকা সিটি কলেজ (Dhaka City College)', slug: 'dhaka-city-college', location: 'ধানমণ্ডি, ঢাকা', shift: 'প্রভাতী (মেয়ে) & দিবা (ছেলে)', type: 'বেসরকারি স্বনামধন্য', scienceGPA: '4.80', commerceGPA: '4.25', artsGPA: '3.50', seats: '২,৫০০+' },
  { collegeName: 'মিরপুর কেন্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ', slug: 'mirpur-cantonment', location: 'মিরপুর কেন্টনমেন্ট, ঢাকা', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'সেনাবাহিনী পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.00', seats: '৮০০+' },
  { collegeName: 'বিএএফ শাহীন কলেজ ঢাকা (BAF Shaheen College)', slug: 'baf-shaheen-dhaka', location: 'কুর্মিটোলা, ঢাকা কেন্টনমেন্ট', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'বিমানবাহিনী পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.00', seats: '১,৬০০+' },
  { collegeName: 'বিএএফ শাহীন কলেজ কুর্মিটোলা', slug: 'baf-shaheen-kurmitola', location: 'কুর্মিটোলা, ঢাকা', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'বিমানবাহিনী পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.40', artsGPA: '3.80', seats: '১,২০০+' },
  { collegeName: 'শহীদ বীর উত্তম লেঃ আনোয়ার গার্লস কলেজ', slug: 'anwar-girls-college', location: 'ঢাকা ক্যান্টনমেন্ট', shift: 'প্রভাতী ও দিবা (ছাত্রী)', type: 'সেনাবাহিনী পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.00', seats: '১,২০০+' },
  { collegeName: 'মতিঝিল সরকারি বালক উচ্চ বিদ্যালয় ও কলেজ', slug: 'motijheel-gov-boys', location: 'মতিঝিল, ঢাকা', shift: 'প্রভাতী ও দিবা (ছাত্র)', type: 'সরকারি', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '3.80', seats: '৭০০+' },
  { collegeName: 'লালমাটিয়া সরকারি মহিলা কলেজ', slug: 'lalmatia-gov-girls', location: 'লালমাটিয়া, ঢাকা', shift: 'প্রভাতী (ছাত্রী)', type: 'সরকারি', scienceGPA: '4.75', commerceGPA: '4.25', artsGPA: '3.50', seats: '১,১০০+' },
  { collegeName: 'ইডেন মহিলা কলেজ (একাদশ শাখা)', slug: 'eden-college-hsc', location: 'আজিমপুর, ঢাকা', shift: 'প্রভাতী (ছাত্রী)', type: 'সরকারি', scienceGPA: '4.80', commerceGPA: '4.30', artsGPA: '3.75', seats: '৮০০+' },
  { collegeName: 'সেন্ট গ্রেগরি হাই স্কুল অ্যান্ড কলেজ', slug: 'st-gregory', location: 'লক্ষ্মীবাজার, পুরান ঢাকা', shift: 'দিবা (ছাত্র)', type: 'মিশন পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.25', artsGPA: '3.50', seats: '৬০০+' },
  { collegeName: 'সেন্ট ফ্রান্সিস জেভিয়ার্স গার্লস স্কুল অ্যান্ড কলেজ', slug: 'st-francis-xavier', location: 'লক্ষ্মীবাজার, পুরান ঢাকা', shift: 'প্রভাতী (ছাত্রী)', type: 'মিশন পরিচালিত', scienceGPA: '4.85', commerceGPA: '4.00', artsGPA: '3.25', seats: '৫০০+' },
  { collegeName: 'মোহাম্মদপুর সরকারি কলেজ', slug: 'mohammadpur-gov-college', location: 'সাতমসজিদ রোড, ঢাকা', shift: 'প্রভাতী ও দিবা', type: 'সরকারি', scienceGPA: '4.75', commerceGPA: '4.25', artsGPA: '3.50', seats: '১,২০০+' },
  { collegeName: 'তেজগাঁও সরকারি কলেজ', slug: 'tejgaon-gov-college', location: 'ফার্মগেট, ঢাকা', shift: 'দিবা ও সান্ধ্য', type: 'সরকারি', scienceGPA: '4.50', commerceGPA: '3.80', artsGPA: '3.25', seats: '১,৫০০+' },
  { collegeName: 'ক্যামব্রিয়ান কলেজ (Cambrian College)', slug: 'cambrian-college', location: 'বারিধারা/উত্তরা, ঢাকা', shift: 'প্রভাতী ও দিবা', type: 'বেসরকারি স্বনামধন্য', scienceGPA: '4.50', commerceGPA: '3.80', artsGPA: '3.25', seats: '২,০০০+' },
  { collegeName: 'উত্তরা হাই স্কুল অ্যান্ড কলেজ', slug: 'uttara-high-school', location: 'উত্তরা, ঢাকা', shift: 'প্রভাতী ও দিবা', type: 'বেসরকারি স্বনামধন্য', scienceGPA: '4.85', commerceGPA: '4.25', artsGPA: '3.75', seats: '১,০০০+' },
];

export const CHATTOGRAM_COLLEGES_REQ: CollegeReqItem[] = [
  { collegeName: 'চট্টগ্রাম কলেজ (Chittagong College)', slug: 'chittagong-college', location: 'চকবাজার, চট্টগ্রাম', shift: 'দিবা (সহশিক্ষা)', type: 'সরকারি ঐতিহ্যবাহী', scienceGPA: '5.00 (Cut Mark 1150+)', commerceGPA: 'N/A', artsGPA: '4.50', seats: '১,০০০+' },
  { collegeName: 'সরকারি হাজী মুহাম্মদ মহসিন কলেজ', slug: 'hajee-mohammad-mohsin', location: 'চকবাজার, চট্টগ্রাম', shift: 'দিবা (সহশিক্ষা)', type: 'সরকারি ঐতিহ্যবাহী', scienceGPA: '5.00 (Cut Mark 1130+)', commerceGPA: '4.75', artsGPA: '4.25', seats: '১,২০০+' },
  { collegeName: 'চট্টগ্রাম সরকারি সিটি কলেজ', slug: 'chittagong-city-college', location: 'আইস ফ্যাক্টরি রোড, চট্টগ্রাম', shift: 'প্রভাতী ও দিবা', type: 'সরকারি', scienceGPA: '4.85', commerceGPA: '4.50', artsGPA: '4.00', seats: '১,৫০০+' },
  { collegeName: 'চট্টগ্রাম সরকারি মহিলা কলেজ', slug: 'chittagong-girls-college', location: 'নাসিরাবাদ, চট্টগ্রাম', shift: 'প্রভাতী (ছাত্রী)', type: 'সরকারি মহিলা', scienceGPA: '4.75', commerceGPA: '4.25', artsGPA: '3.75', seats: '১,১০০+' },
  { collegeName: 'ক্যান্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ চট্টগ্রাম', slug: 'cantonment-public-chittagong', location: 'বায়েজিদ, চট্টগ্রাম কেন্টনমেন্ট', shift: 'প্রভাতী ও দিবা', type: 'সেনাবাহিনী পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.00', seats: '৮০০+' },
  { collegeName: 'চট্টগ্রাম কেন্টনমেন্ট পাবলিক কলেজ (CCPC)', slug: 'ccpc-chittagong', location: 'চট্টগ্রাম কেন্টনমেন্ট', shift: 'প্রভাতী ও দিবা (সহশিক্ষা)', type: 'সেনাবাহিনী পরিচালিত', scienceGPA: '5.00', commerceGPA: '4.60', artsGPA: '4.00', seats: '১,২০০+' },
  { collegeName: 'কুমিল্লা ভিক্টোরিয়া সরকারি কলেজ', slug: 'comilla-victoria-college', location: 'কান্দিরপাড়, কুমিল্লা', shift: 'দিবা (সহশিক্ষা)', type: 'সরকারি ঐতিহ্যবাহী', scienceGPA: '5.00', commerceGPA: '4.65', artsGPA: '4.25', seats: '১,৫০০+' },
  { collegeName: 'ফেনী সরকারি কলেজ', slug: 'feni-gov-college', location: 'ফেনী সদর', shift: 'দিবা', type: 'সরকারি', scienceGPA: '4.85', commerceGPA: '4.25', artsGPA: '3.75', seats: '১,১০০+' },
  { collegeName: 'নোয়াখালী সরকারি কলেজ', slug: 'noakhali-gov-college', location: 'মাইজদী কোর্ট, নোয়াখালী', shift: 'দিবা', type: 'সরকারি', scienceGPA: '4.85', commerceGPA: '4.25', artsGPA: '3.80', seats: '১,২০০+' },
  { collegeName: 'কক্সবাজার সরকারি কলেজ', slug: 'coxsbazar-gov-college', location: 'লিংক রোড, কক্সবাজার', shift: 'দিবা', type: 'সরকারি', scienceGPA: '4.75', commerceGPA: '4.00', artsGPA: '3.50', seats: '১,০০০+' },
  { collegeName: 'চাঁদপুর সরকারি কলেজ', slug: 'chandpur-gov-college', location: 'স্টেডিয়াম রোড, চাঁদপুর', shift: 'দিবা', type: 'সরকারি', scienceGPA: '4.75', commerceGPA: '4.00', artsGPA: '3.50', seats: '৯০০+' },
  { collegeName: 'পটিয়া সরকারি কলেজ', slug: 'patiya-gov-college', location: 'পটিয়া, চট্টগ্রাম', shift: 'দিবা', type: 'সরকারি', scienceGPA: '4.50', commerceGPA: '3.75', artsGPA: '3.25', seats: '৮০০+' },
];

export const DIVISION_COLLEGES_REQ: DivisionRequirement[] = [
  {
    division: 'ঢাকা বিভাগ (Dhaka Division - সেরা ৩০টি কলেজ)',
    slug: 'dhaka-division',
    bnName: 'ঢাকা বিভাগ',
    colleges: TOP_DHAKA_COLLEGES_REQ,
  },
  {
    division: 'চট্টগ্রাম বিভাগ (Chattogram Division - সেরা ১২টি কলেজ)',
    slug: 'chattogram-division',
    bnName: 'চট্টগ্রাম বিভাগ',
    colleges: CHATTOGRAM_COLLEGES_REQ,
  },
  {
    division: 'রাজশাহী বিভাগ (Rajshahi Division)',
    slug: 'rajshahi-division',
    bnName: 'রাজশাহী বিভাগ',
    colleges: [
      { collegeName: 'রাজশাহী কলেজ (Rajshahi College)', slug: 'rajshahi-college', location: 'রাজশাহী সদর', shift: 'দিবা (সহশিক্ষা)', scienceGPA: '5.00 (Cut Mark 1155+)', commerceGPA: '4.75', artsGPA: '4.50', seats: '১,১০০+' },
      { collegeName: 'রাজশাহী সরকারি সিটি কলেজ', location: 'রাজশাহী', shift: 'প্রভাতী ও দিবা', scienceGPA: '4.90', commerceGPA: '4.50', artsGPA: '4.00', seats: '১,২০০+' },
      { collegeName: 'বগুড়া সরকারি আজিজুল হক কলেজ', location: 'বগুড়া', shift: 'দিবা', scienceGPA: '5.00', commerceGPA: '4.65', artsGPA: '4.25', seats: '১,৪০০+' },
    ],
  },
  {
    division: 'খুলনা বিভাগ (Khulna Division)',
    slug: 'khulna-division',
    bnName: 'খুলনা বিভাগ',
    colleges: [
      { collegeName: 'সরকারি বিএল কলেজ (BL College)', slug: 'bl-college', location: 'দৌলতপুর, খুলনা', shift: 'দিবা', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.00', seats: '১,২০০+' },
      { collegeName: 'খুলনা সরকারি মজিদ মেমোরিয়াল সিটি কলেজ', location: 'খুলনা', shift: 'দিবা', scienceGPA: '4.85', commerceGPA: '4.25', artsGPA: '3.75', seats: '১,০০০+' },
    ],
  },
  {
    division: 'বরিশাল বিভাগ (Barishal Division)',
    slug: 'barishal-division',
    bnName: 'বরিশাল বিভাগ',
    colleges: [
      { collegeName: 'সরকারি ব্রজমোহন (বিএম) কলেজ', slug: 'bm-college', location: 'বরিশাল', shift: 'দিবা', scienceGPA: '4.90', commerceGPA: '4.35', artsGPA: '4.00', seats: '১,৩০০+' },
      { collegeName: 'বরিশাল সরকারি মহিলা কলেজ', location: 'বরিশাল', shift: 'প্রভাতী', scienceGPA: '4.75', commerceGPA: '4.15', artsGPA: '3.75', seats: '১,০০০+' },
    ],
  },
  {
    division: 'সিলেট বিভাগ (Sylhet Division)',
    slug: 'sylhet-division',
    bnName: 'সিলেট বিভাগ',
    colleges: [
      { collegeName: 'সিলেট এমসি কলেজ (MC College)', slug: 'mc-college', location: 'টিলাগড়, সিলেট', shift: 'দিবা', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.25', seats: '১,২০০+' },
      { collegeName: 'সিলেট সরকারি মহিলা কলেজ', location: 'চৌহাট্টা, সিলেট', shift: 'প্রভাতী', scienceGPA: '4.80', commerceGPA: '4.25', artsGPA: '3.80', seats: '১,১০০+' },
    ],
  },
  {
    division: 'রংপুর বিভাগ (Rangpur Division)',
    slug: 'rangpur-division',
    bnName: 'রংপুর বিভাগ',
    colleges: [
      { collegeName: 'রংপুর কারমাইকেল কলেজ (Carmichael College)', slug: 'carmichael-college', location: 'রংপুর', shift: 'দিবা', scienceGPA: '5.00', commerceGPA: '4.50', artsGPA: '4.25', seats: '১,৪০০+' },
      { collegeName: 'রংপুর সরকারি কলেজ', location: 'রংপুর', shift: 'দিবা', scienceGPA: '4.85', commerceGPA: '4.30', artsGPA: '3.85', seats: '১,১০০+' },
    ],
  },
  {
    division: 'ময়মনসিংহ বিভাগ (Mymensingh Division)',
    slug: 'mymensingh-division',
    bnName: 'ময়মনসিংহ বিভাগ',
    colleges: [
      { collegeName: 'ময়মনসিংহ আনন্দ মোহন কলেজ', slug: 'ananda-mohan-college', location: 'ময়মনসিংহ', shift: 'দিবা', scienceGPA: '5.00', commerceGPA: '4.60', artsGPA: '4.25', seats: '১,৩০০+' },
    ],
  },
];

// Detailed College Interface for Individual College SEO Pages
export interface DetailedCollege {
  slug: string;
  name: string;
  bnName: string;
  eiin?: string;
  established?: string;
  location: string;
  division: string;
  divisionSlug: string;
  shift: string;
  type: string;
  gender: string;
  image?: string;
  principalMessage?: string;
  scienceGPA: string;
  commerceGPA: string;
  artsGPA: string;
  seatsScience: string;
  seatsCommerce: string;
  seatsArts: string;
  totalSeats: string;
  description: string;
  address: string;
  website?: string;
}

export const DETAILED_COLLEGES_LIST: DetailedCollege[] = [
  {
    slug: 'ideal-motijheel',
    name: 'Ideal School & College Motijheel',
    bnName: 'আইডিয়াল স্কুল অ্যান্ড কলেজ মতিঝিল',
    eiin: '১০৮২৭৩',
    established: '১৯৬৫',
    location: 'মতিঝিল, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (সহশিক্ষা)',
    type: 'বেসরকারি স্বনামধন্য',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'মতিঝিল আইডিয়াল স্কুল অ্যান্ড কলেজ মেধা ও শৃঙ্খলার সাথে বোর্ড পরীক্ষায় সর্বোচ্চ ফলাফল নিশ্চিত করে থাকে।',
    scienceGPA: '5.00 (Total Marks 1135+)',
    commerceGPA: '4.75',
    artsGPA: '4.00',
    seatsScience: '১,০০০',
    seatsCommerce: '৩৫০',
    seatsArts: '১৫০',
    totalSeats: '১,৫০০',
    description: 'মতিঝিলে অবস্থিত আইডিয়াল স্কুল অ্যান্ড কলেজ রাজধানী ঢাকার অন্যতম ঐতিহ্যবাহী ও বৃহৎ আকারের শিক্ষা প্রতিষ্ঠান।',
    address: 'মতিঝিল, ঢাকা – ১০০০',
    website: 'https://idealschoolandcollege.edu.bd',
  },
  {
    slug: 'dhaka-college',
    name: 'Dhaka College',
    bnName: 'ঢাকা কলেজ',
    eiin: '১০৭৯৭৭',
    established: '১৮৪১',
    location: 'নিউ মার্কেট, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'দিবা (ছাত্র)',
    type: 'সরকারি',
    gender: 'ছাত্র (Male Only)',
    principalMessage: '১৮৪১ সালে প্রতিষ্ঠিত উপমহাদেশের অন্যতম প্রাচীন ও ঐতিহ্যবাহী শিক্ষা প্রতিষ্ঠান ঢাকা কলেজ।',
    scienceGPA: '5.00 (Total Marks 1150+)',
    commerceGPA: '4.75',
    artsGPA: '4.25',
    seatsScience: '৯০০',
    seatsCommerce: '১৫০',
    seatsArts: '১৫০',
    totalSeats: '১,২০০',
    description: '১৮৪১ সালে প্রতিষ্ঠিত উপমহাদেশের অন্যতম প্রাচীন ও ঐতিহ্যবাহী শিক্ষা প্রতিষ্ঠান ঢাকা কলেজ। উচ্চ মাধ্যমিক পর্যায়ে কেবল ছেলেদের জন্য মানসম্মত শিক্ষা প্রদান করা হয়।',
    address: 'মিরপুর রোড, নিউ মার্কেট, ঢাকা – ১২০৫',
    website: 'https://dhakacollege.edu.bd',
  },
  {
    slug: 'viqarunnisa-noon',
    name: 'Viqarunnisa Noon School & College',
    bnName: 'ভিকারুননিসা নূন স্কুল অ্যান্ড কলেজ',
    eiin: '১০৮৩৫৮',
    established: '১৯৫২',
    location: 'বেইলি রোড, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (ছাত্রী)',
    type: 'বেসরকারি স্বনামধন্য',
    gender: 'ছাত্রী (Female Only)',
    principalMessage: 'মেধা ও শৃঙ্খলায় ভিকারুননিসা নূন কলেজ প্রতি বছর এইচএসসি পরীক্ষায় অনন্য কৃতিত্ব অর্জন করে।',
    scienceGPA: '5.00 (Total Marks 1140+)',
    commerceGPA: '4.75',
    artsGPA: '4.25',
    seatsScience: '১,৪০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '২,০০০',
    description: 'বাংলাদেশের অন্যতম শ্রেষ্ঠ বালিকা বিদ্যালয় ও কলেজ। মেধা ও শৃঙ্খলায় ভিকারুননিসা নূন কলেজ প্রতি বছর এইচএসসি পরীক্ষায় অনন্য কৃতিত্ব অর্জন করে।',
    address: '১/এ নিউ বেইলি রোড, ঢাকা – ১০০০',
    website: 'https://vnsc.edu.bd',
  },
  {
    slug: 'rajuk-uttara-model',
    name: 'Rajuk Uttara Model College',
    bnName: 'রাজউক উত্তরা মডেল কলেজ',
    eiin: '১০৮৫৭৩',
    established: '১৯৯৪',
    location: 'উত্তরা, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (সহশিক্ষা)',
    type: 'সরকারি ট্রাস্ট',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'রাজধানীর উত্তরায় অবস্থিত রাজউক উত্তরা মডেল কলেজ দেশজুড়ে তার কঠোর শৃঙ্খলা ও ঈর্ষণীয় ফলাফলের জন্য পরিচিত।',
    scienceGPA: '5.00 (Total Marks 1160+)',
    commerceGPA: '4.85',
    artsGPA: '4.50',
    seatsScience: '৮০০',
    seatsCommerce: '২০০',
    seatsArts: '১০০',
    totalSeats: '১,১০০',
    description: 'রাজধানীর উত্তরায় অবস্থিত রাজউক উত্তরা মডেল কলেজ দেশজুড়ে তার কঠোর শৃঙ্খলা ও ঈর্ষণীয় বোর্ডের ফলাফলের জন্য সুপরিচিত।',
    address: 'সেক্টর ৬, উত্তরা মডেল টাউন, ঢাকা – ১২৩০',
    website: 'https://rumc.edu.bd',
  },
  {
    slug: 'adamjee-cantonment',
    name: 'Adamjee Cantonment College',
    bnName: 'আদমজী ক্যান্টনমেন্ট কলেজ',
    eiin: '১০৭৮৫৫',
    established: '১৯৬০',
    location: 'ঢাকা ক্যান্টনমেন্ট',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (সহশিক্ষা)',
    type: 'সেনাবাহিনী পরিচালিত',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'বাংলাদেশ সেনাবাহিনী পরিচালিত আদমজী ক্যান্টনমেন্ট কলেজ দেশের অন্যতম সেরা শিক্ষা প্রতিষ্ঠান।',
    scienceGPA: '5.00 (Total Marks 1130+)',
    commerceGPA: '4.75',
    artsGPA: '4.25',
    seatsScience: '১,২০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,৮০০',
    description: 'বাংলাদেশ সেনাবাহিনী কর্তৃক পরিচালিত আদমজী ক্যান্টনমেন্ট কলেজ দেশের অন্যতম সেরা শিক্ষা প্রতিষ্ঠান। আধুনিক ল্যাব ও সহপাঠ কার্যক্রমে বিশ্বমানের পরিবেশ বিদ্যমান।',
    address: 'ঢাকা ক্যান্টনমেন্ট, ঢাকা – ১২০৬',
    website: 'https://acc.edu.bd',
  },
  {
    slug: 'government-science-college',
    name: 'Government Science College',
    bnName: 'সরকারি বিজ্ঞান কলেজ',
    eiin: '১০৮১৬২',
    established: '১৯৫৪',
    location: 'ফার্মগেট, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'দিবা (ছাত্র)',
    type: 'সরকারি বিশেষায়িত',
    gender: 'ছাত্র (Male Only)',
    principalMessage: 'বিজ্ঞান শিক্ষায় গুণগত পরিবর্তন আনাই সরকারি বিজ্ঞান কলেজের মূল আদর্শ।',
    scienceGPA: '5.00 (Total Marks 1120+)',
    commerceGPA: 'N/A',
    artsGPA: 'N/A',
    seatsScience: '১,২০০',
    seatsCommerce: '০',
    seatsArts: '০',
    totalSeats: '১,২০০',
    description: 'কেবল বিজ্ঞান বিভাগের শিক্ষার্থীদের জন্য ঢাকা শহরে অবস্থিত সেরা সরকারি বিশেষায়িত কলেজ হলো সরকারি বিজ্ঞান কলেজ।',
    address: 'ফার্মগেট, তেজগাঁও, ঢাকা – ১২১৫',
    website: 'https://gsc.edu.bd',
  },
  {
    slug: 'residential-model',
    name: 'Dhaka Residential Model College',
    bnName: 'ঢাকা রেসিডেনসিয়াল মডেল কলেজ',
    eiin: '১০৮২৩৭',
    established: '১৯৬০',
    location: 'মোহাম্মদপুর, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (ছাত্র)',
    type: 'সরকারি ট্রাস্ট',
    gender: 'ছাত্র (Male Only)',
    principalMessage: 'সবুজ শালঘেরা প্রাকৃতিক পরিবেশে ছেলেদের আদর্শ মানুষ বানাতে রেসিডেনসিয়াল মডেল কলেজ বদ্ধপরিকর।',
    scienceGPA: '5.00 (Total Marks 1145+)',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '৭০০',
    seatsCommerce: '২০০',
    seatsArts: '১০০',
    totalSeats: '১,০০০',
    description: 'সবুজ ও বিশাল ক্যাম্পাস জুড়ে অবস্থিত আবাসিক ও অনাবাসিক ছেলেদের দেশের বিখ্যাত মডেল কলেজ।',
    address: 'মিরপুর রোড, মোহাম্মদপুর, ঢাকা – ১২০৭',
    website: 'https://drmc.edu.bd',
  },
  {
    slug: 'dhaka-city-college',
    name: 'Dhaka City College',
    bnName: 'ঢাকা সিটি কলেজ',
    eiin: '১০৭৯৭৫',
    established: '১৯৫৭',
    location: 'ধানমণ্ডি, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী (মেয়ে) & দিবা (ছেলে)',
    type: 'বেসরকারি স্বনামধন্য',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'ধানমন্ডি এলাকায় আধুনিক পদ্ধতিতে পাঠদানের মাধ্যমে সিটি কলেজ বহু বছর ধরে সুনাম ধরে রেখেছে।',
    scienceGPA: '4.80',
    commerceGPA: '4.25',
    artsGPA: '3.50',
    seatsScience: '১,২০০',
    seatsCommerce: '১,০০০',
    seatsArts: '৩০০',
    totalSeats: '২,৫০০',
    description: 'ধানমন্ডি এলাকায় অবস্থিত দেশের অন্যতম বৃহত্তম ও সফল বেসরকারি উচ্চ মাধ্যমিক কলেজ।',
    address: 'কুদরাত-ই-খুদা রোড, ধানমণ্ডি, ঢাকা – ১২০৫',
    website: 'https://dhakacitycollege.edu.bd',
  },
  {
    slug: 'mirpur-cantonment',
    name: 'Mirpur Cantonment Public School & College',
    bnName: 'মিরপুর কেন্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ',
    eiin: '১৩৬৭৯৫',
    established: '২০১৪',
    location: 'মিরপুর কেন্টনমেন্ট, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'সেনাবাহিনী পরিচালিত',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'মিরপুর ডিওএইচএস সংলগ্ন সেনাবাহিনী পরিচালিত আধুনিক সুবিধাসম্পন্ন মডেল কলেজ।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '৫০০',
    seatsCommerce: '২০০',
    seatsArts: '১০০',
    totalSeats: '৮০০',
    description: 'মিরপুর ডিওএইচএস এলাকায় অবস্থিত সেনাবাহিনী পরিচালিত দেশের অন্যতম আধুনিক পাবলিক স্কুল অ্যান্ড কলেজ।',
    address: 'মিরপুর কেন্টনমেন্ট, ঢাকা – ১২১৬',
    website: 'https://mcpsc.edu.bd',
  },
  {
    slug: 'baf-shaheen-dhaka',
    name: 'BAF Shaheen College Dhaka',
    bnName: 'বিএএফ শাহীন কলেজ ঢাকা',
    eiin: '১০৭৮৫৬',
    established: '১৯৬০',
    location: 'কুর্মিটোলা, ঢাকা কেন্টনমেন্ট',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'বিমানবাহিনী পরিচালিত',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'শিক্ষা, সংযম ও শৃঙ্খলা—এই স্লোগানকে সামনে রেখে বাংলাদেশ বিমান বাহিনী পরিচালিত শাহীন কলেজ ঢাকা।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '১,০০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,৬০০',
    description: 'জাহাঙ্গীর গেট সংলগ্ন বাংলাদেশ বিমান বাহিনী পরিচালিত বিখ্যাত বিএএফ শাহীন কলেজ ঢাকা।',
    address: 'ঢাকা কেন্টনমেন্ট, ঢাকা – ১২০৬',
    website: 'https://bafsd.edu.bd',
  },
  {
    slug: 'baf-shaheen-kurmitola',
    name: 'BAF Shaheen College Kurmitola',
    bnName: 'বিএএফ শাহীন কলেজ কুর্মিটোলা',
    eiin: '১০৭৮৫৭',
    established: '১৯৮২',
    location: 'কুর্মিটোলা, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'বিমানবাহিনী পরিচালিত',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'কুর্মিটোলা বিমান বাহিনী ঘাঁটিতে অবস্থিত অন্যতম প্রধান শাহীন কলেজ।',
    scienceGPA: '5.00',
    commerceGPA: '4.40',
    artsGPA: '3.80',
    seatsScience: '৭০০',
    seatsCommerce: '৩০০',
    seatsArts: '২০০',
    totalSeats: '১,২০০',
    description: 'কুর্মিটোলা বিমান বাহিনী ঘাঁটি সংলগ্ন স্বনামধন্য বিএএফ শাহীন কলেজ।',
    address: 'কুর্মিটোলা, ঢাকা কেন্টনমেন্ট – ১২০৬',
    website: 'https://bafsk.edu.bd',
  },
  {
    slug: 'anwar-girls-college',
    name: 'Shaheed Bir Uttam Lt. Anwar Girls College',
    bnName: 'শহীদ বীর উত্তম লেঃ আনোয়ার গার্লস কলেজ',
    eiin: '১০৭৮৫৮',
    established: '১৯৫৭',
    location: 'ঢাকা ক্যান্টনমেন্ট',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (ছাত্রী)',
    type: 'সেনাবাহিনী পরিচালিত',
    gender: 'ছাত্রী (Female Only)',
    principalMessage: 'মেয়েদের জন্য সেনানিয়ন্ত্রিত অন্যতম সেরা ও সুশৃঙ্খল মহিলা কলেজ।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '৭০০',
    seatsCommerce: '৩০০',
    seatsArts: '২০০',
    totalSeats: '১,২০০',
    description: 'ঢাকা সেনানিবাসে অবস্থিত মেয়েদের সেরা সেনাবাহিনী পরিচালিত আনোয়ার গার্লস কলেজ।',
    address: 'ঢাকা ক্যান্টনমেন্ট, ঢাকা – ১২০৬',
    website: 'https://sagc.edu.bd',
  },
  {
    slug: 'motijheel-gov-boys',
    name: 'Motijheel Government Boys High School & College',
    bnName: 'মতিঝিল সরকারি বালক উচ্চ বিদ্যালয় ও কলেজ',
    eiin: '১০৮২২৪',
    established: '১৯৫৭',
    location: 'মতিঝিল, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা (ছাত্র)',
    type: 'সরকারি',
    gender: 'ছাত্র (Male Only)',
    principalMessage: 'মতিঝিল এলাকায় সরকারি ব্যবস্থাপনায় মানসম্মত শিক্ষা প্রদানে আমরা অঙ্গীকারবদ্ধ।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '3.80',
    seatsScience: '৪০০',
    seatsCommerce: '২০০',
    seatsArts: '১০০',
    totalSeats: '৭০০',
    description: 'মতিঝিলে অবস্থিত ছেলেদের ঐতিহ্যবাহী সরকারি স্কুল অ্যান্ড কলেজ।',
    address: 'আউটার সার্কুলার রোড, মতিঝিল, ঢাকা – ১০০০',
    website: 'https://mgbhsc.edu.bd',
  },
  {
    slug: 'lalmatia-gov-girls',
    name: 'Lalmatia Government Women\'s College',
    bnName: 'লালমাটিয়া সরকারি মহিলা কলেজ',
    eiin: '১০৮২৫০',
    established: '১৯৬৬',
    location: 'লালমাটিয়া, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী (ছাত্রী)',
    type: 'সরকারি',
    gender: 'ছাত্রী (Female Only)',
    principalMessage: 'লালমাটিয়া এলাকায় মেয়েদের সরকারি মেধা বিকাশ কেন্দ্র হিসেবে লালমাটিয়া মহিলা কলেজ পরিচিত।',
    scienceGPA: '4.75',
    commerceGPA: '4.25',
    artsGPA: '3.50',
    seatsScience: '৫০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,১০০',
    description: 'লালমাটিয়া এলাকায় অবস্থিত মেয়েদের ঐতিহ্যবাহী সরকারি মহিলা কলেজ।',
    address: 'ব্লক বি, লালমাটিয়া, ঢাকা – ১২০৭',
    website: 'https://lgwc.edu.bd',
  },
  {
    slug: 'eden-college-hsc',
    name: 'Eden Mohila College (HSC Section)',
    bnName: 'ইডেন মহিলা কলেজ (একাদশ শাখা)',
    eiin: '১০৭৯৭৬',
    established: '১৮৭৩',
    location: 'আজিমপুর, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী (ছাত্রী)',
    type: 'সরকারি',
    gender: 'ছাত্রী (Female Only)',
    principalMessage: '১৮৭৩ সালে প্রতিষ্ঠিত এশিয়ার বিখ্যাত নারী শিক্ষা নিকেতন ইডেন মহিলা কলেজ।',
    scienceGPA: '4.80',
    commerceGPA: '4.30',
    artsGPA: '3.75',
    seatsScience: '৪০০',
    seatsCommerce: '২৫০',
    seatsArts: '১৫০',
    totalSeats: '৮০০',
    description: 'আজিমপুরে অবস্থিত নারী শিক্ষার শীর্ষ সরকারি কলেজ ইডেন মহিলা কলেজ।',
    address: 'আজিমপুর রোড, ঢাকা – ১২০৫',
    website: 'https://emc.edu.bd',
  },
  {
    slug: 'st-gregory',
    name: 'St. Gregory\'s High School & College',
    bnName: 'সেন্ট গ্রেগরি হাই স্কুল অ্যান্ড কলেজ',
    eiin: '১০৮১৫৭',
    established: '১৮৮২',
    location: 'লক্ষ্মীবাজার, পুরান ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'দিবা (ছাত্র)',
    type: 'মিশন পরিচালিত',
    gender: 'ছাত্র (Male Only)',
    principalMessage: '১৮৮২ সালে প্রতিষ্ঠিত পুরান ঢাকার বিখ্যাত মিশনারি ক্যাথলিক স্কুল অ্যান্ড কলেজ।',
    scienceGPA: '5.00',
    commerceGPA: '4.25',
    artsGPA: '3.50',
    seatsScience: '৪০০',
    seatsCommerce: '১৫০',
    seatsArts: '৫০',
    totalSeats: '৬০০',
    description: 'পুরান ঢাকার লক্ষ্মীবাজারে অবস্থিত ১৮৮২ সালের ঐতিহাসিক মিশন পরিচালিত সেন্ট গ্রেগরি।',
    address: 'লক্ষ্মীবাজার, ঢাকা – ১১০০',
    website: 'https://sghsc.edu.bd',
  },
  {
    slug: 'st-francis-xavier',
    name: 'St. Francis Xavier\'s Girls School & College',
    bnName: 'সেন্ট ফ্রান্সিস জেভিয়ার্স গার্লস স্কুল অ্যান্ড কলেজ',
    eiin: '১০৮১৫৮',
    established: '১৯১২',
    location: 'লক্ষ্মীবাজার, পুরান ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী (ছাত্রী)',
    type: 'মিশন পরিচালিত',
    gender: 'ছাত্রী (Female Only)',
    principalMessage: 'পুরান ঢাকায় মেয়েদের নৈতিকতা ও শিক্ষার মান নিশ্চিত করায় সেন্ট ফ্রান্সিস জেভিয়ার্স পরিচিত।',
    scienceGPA: '4.85',
    commerceGPA: '4.00',
    artsGPA: '3.25',
    seatsScience: '৩০০',
    seatsCommerce: '১৫০',
    seatsArts: '৫০',
    totalSeats: '৫০০',
    description: 'পুরান ঢাকায় অবস্থিত ১৯১২ সালে প্রতিষ্ঠিত বিখ্যাত মিশনারি বালিকা কলেজ।',
    address: 'লক্ষ্মীবাজার, পুরান ঢাকা – ১১০০',
    website: 'https://sfxs.edu.bd',
  },
  {
    slug: 'mohammadpur-gov-college',
    name: 'Mohammadpur Government College',
    bnName: 'মোহাম্মদপুর সরকারি কলেজ',
    eiin: '১০৮২৫৪',
    established: '১৯৬৬',
    location: 'সাতমসজিদ রোড, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'মোহাম্মদপুর এলাকায় সরকারি ব্যবস্থাপনায় মানসম্মত শিক্ষা সেবা দিয়ে আসছে কলেজটি।',
    scienceGPA: '4.75',
    commerceGPA: '4.25',
    artsGPA: '3.50',
    seatsScience: '৬০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,২০০',
    description: 'মোহাম্মদপুর এলাকায় অবস্থিত ঢাকা শিক্ষাবোর্ডের স্বনামধন্য সরকারি কলেজ।',
    address: 'সাতমসজিদ রোড, ধানমণ্ডি, ঢাকা – ১২০৭',
    website: 'https://mgc.edu.bd',
  },
  {
    slug: 'tejgaon-gov-college',
    name: 'Tejgaon Government College',
    bnName: 'তেজগাঁও সরকারি কলেজ',
    eiin: '১০৮২৫৩',
    established: '১৯৬১',
    location: 'ফার্মগেট, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'দিবা ও সান্ধ্য',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'ফার্মগেট এলাকায় অবস্থিত অন্যতম বড় সরকারি কলেজ তেজগাঁও সরকারি কলেজ।',
    scienceGPA: '4.50',
    commerceGPA: '3.80',
    artsGPA: '3.25',
    seatsScience: '৭০০',
    seatsCommerce: '৫০০',
    seatsArts: '৩০০',
    totalSeats: '১,৫০০',
    description: 'ফার্মগেটে অবস্থিত ১৯৬১ সালের সরকারি কলেজ।',
    address: 'ফার্মগেট, তেজগাঁও, ঢাকা – ১২১৫',
    website: 'https://tgc.edu.bd',
  },
  {
    slug: 'cambrian-college',
    name: 'Cambrian College Dhaka',
    bnName: 'ক্যামব্রিয়ান কলেজ ঢাকা',
    eiin: '১৩২০০১',
    established: '২০০৪',
    location: 'বারিধারা/উত্তরা, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'বেসরকারি স্বনামধন্য',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'স্মার্ট ক্লাসরুম ও ডিজিটাল ল্যাব এর মাধ্যমে পড়াশোনায় ভালো ফলাফল নিশ্চিতে ক্যামব্রিয়ান কলেজ প্রতিশ্রুতিবদ্ধ।',
    scienceGPA: '4.50',
    commerceGPA: '3.80',
    artsGPA: '3.25',
    seatsScience: '১,০০০',
    seatsCommerce: '৭০০',
    seatsArts: '৩০০',
    totalSeats: '২,০০০',
    description: 'ডিজিটাল শিক্ষা পদ্ধতির আধুনিক বেসরকারি কলেজ ক্যামব্রিয়ান কলেজ।',
    address: 'নর্দা, বারিধারা, ঢাকা – ১২১২',
    website: 'https://cambrian.edu.bd',
  },
  {
    slug: 'uttara-high-school',
    name: 'Uttara High School & College',
    bnName: 'উত্তরা হাই স্কুল অ্যান্ড কলেজ',
    eiin: '১০৮৫৮৪',
    established: '১৯৮৫',
    location: 'উত্তরা, ঢাকা',
    division: 'Dhaka Division',
    divisionSlug: 'dhaka-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'বেসরকারি স্বনামধন্য',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'উত্তরা মডেল টাউনে মানসম্মত ফলাফলের অন্যতম প্রাচীন বেসরকারি কলেজ।',
    scienceGPA: '4.85',
    commerceGPA: '4.25',
    artsGPA: '3.75',
    seatsScience: '৫০০',
    seatsCommerce: '৩০০',
    seatsArts: '২০০',
    totalSeats: '১,০০০',
    description: 'উত্তরা ৭ নম্বর সেক্টরে অবস্থিত স্বনামধন্য উচ্চ মাধ্যমিক বিদ্যালয় ও কলেজ।',
    address: 'রোর্ড ২৭, সেক্টর ৭, উত্তরা, ঢাকা – ১২৩০',
    website: 'https://uhsc.edu.bd',
  },
  {
    slug: 'chittagong-college',
    name: 'Chittagong College',
    bnName: 'চট্টগ্রাম কলেজ',
    eiin: '১০৪২৭২',
    established: '১৮৬৯',
    location: 'চকবাজার, চট্টগ্রাম',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি ঐতিহ্যবাহী',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'চট্টগ্রাম কলেজ কেবল একটি শিক্ষা প্রতিষ্ঠান নয়, এটি চট্টগ্রাম অঞ্চলের সমৃদ্ধ ইতিহাস ও ঐতিহ্যের স্মারক। মেধা, আদর্শ ও নৈতিক মূল্যবোধের চর্চার মাধ্যমে শিক্ষার্থীদের সুনাগরিক হিসেবে গড়ে তোলাই আমাদের লক্ষ্য।',
    scienceGPA: '5.00 (Cut Mark 1150+)',
    commerceGPA: 'N/A',
    artsGPA: '4.50',
    seatsScience: '৮০০',
    seatsCommerce: '০',
    seatsArts: '২০০',
    totalSeats: '১,০০০',
    description: '১৮৬৯ সালে প্রতিষ্ঠিত ঐতিহ্যবাহী চট্টগ্রাম কলেজ। চট্টগ্রাম বিভাগের সেরা জিপিএ অর্জনকারী শিক্ষার্থীদের প্রথম পছন্দ চট্টগ্রাম কলেজ। উচ্চ মাধ্যমিক বিজ্ঞান ও মানবিক শাখায় সেরা শিক্ষা পরিবেশ বিদ্যমান।',
    address: 'কলেজ রোড, চকবাজার, চট্টগ্রাম – ৪০০০',
    website: 'https://chittagongcollege.edu.bd',
  },
  {
    slug: 'hajee-mohammad-mohsin',
    name: 'Government Haji Mohammad Mohsin College',
    bnName: 'সরকারি হাজী মুহাম্মদ মহসিন কলেজ',
    eiin: '১০৪২৭৩',
    established: '১৮৭৪',
    location: 'চকবাজার, চট্টগ্রাম',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি ঐতিহ্যবাহী',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'দানবীর হাজী মুহাম্মদ মহসিনের নামাঙ্কিত এই প্রাচীন বিদ্যাপিঠে উচ্চমানের শিক্ষা নিশ্চিত করা হয়। শৃঙ্খলার সাথে পড়ালেখা ও জ্ঞান অর্জনে আমরা প্রতিশ্রুতবদ্ধ।',
    scienceGPA: '5.00 (Cut Mark 1130+)',
    commerceGPA: '4.75',
    artsGPA: '4.25',
    seatsScience: '৬০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,২০০',
    description: '১৮৭৪ সালে প্রতিষ্ঠিত দানবীর হাজী মুহাম্মদ মহসিনের স্মৃতিবিজড়িত অন্যতম প্রাচীন সরকারি কলেজ।',
    address: 'কলেজ রোড, চকবাজার, চট্টগ্রাম – ৪০০০',
    website: 'https://mohsincollege.edu.bd',
  },
  {
    slug: 'chittagong-city-college',
    name: 'Government City College Chattogram',
    bnName: 'চট্টগ্রাম সরকারি সিটি কলেজ',
    eiin: '১০৪২৭৪',
    established: '১৯৫৪',
    location: 'আইস ফ্যাক্টরি রোড, চট্টগ্রাম',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'চট্টগ্রাম শহরের প্রাণকেন্দ্রে অবস্থিত সিটি কলেজে আমরা আধুনিক বিজ্ঞানাগার ও ডিজিটাল ক্লাসরুমের মাধ্যমে শিক্ষার্থীদের পড়ালেখা তদারকি করি।',
    scienceGPA: '4.85',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '৬০০',
    seatsCommerce: '৬০০',
    seatsArts: '৩০০',
    totalSeats: '১,৫০০',
    description: '১৯৫৪ সালে প্রতিষ্ঠিত চট্টগ্রাম সরকারি সিটি কলেজ শহরের ব্যস্ততম কেন্দ্রস্থলে বিশাল ক্যাম্পাসে শিক্ষা সেবা দিয়ে আসছে।',
    address: 'আইস ফ্যাক্টরি রোড, চট্টগ্রাম – ৪০০০',
    website: 'https://gccc.edu.bd',
  },
  {
    slug: 'chittagong-girls-college',
    name: 'Government Women\'s College Chattogram',
    bnName: 'চট্টগ্রাম সরকারি মহিলা কলেজ',
    eiin: '১০৪২৮২',
    established: '১৯৫৭',
    location: 'নাসিরাবাদ, চট্টগ্রাম',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'প্রভাতী (ছাত্রী)',
    type: 'সরকারি মহিলা',
    gender: 'ছাত্রী (Female Only)',
    principalMessage: 'নারী শিক্ষার প্রসারে চট্টগ্রাম সরকারি মহিলা কলেজ চট্টগ্রাম বিভাগে শীর্ষে অবস্থান করছে। নিরাপদ ও সুশৃঙ্খল পরিবেশে পাঠদান আমাদের অঙ্গীকার।',
    scienceGPA: '4.75',
    commerceGPA: '4.25',
    artsGPA: '3.75',
    seatsScience: '৫০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,১০০',
    description: 'মেয়েদের জন্য চট্টগ্রাম বিভাগের সেরা সরকারি মহিলা কলেজ হল চট্টগ্রাম সরকারি মহিলা কলেজ।',
    address: 'নাসিরাবাদ, চট্টগ্রাম – ৪০০০',
    website: 'https://cgwc.edu.bd',
  },
  {
    slug: 'cantonment-public-chittagong',
    name: 'Cantonment Public School and College Chattogram',
    bnName: 'ক্যান্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ চট্টগ্রাম',
    eiin: '১০৪৫৮১',
    established: '১৯৬১',
    location: 'বায়েজিদ, চট্টগ্রাম কেন্টনমেন্ট',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'প্রভাতী ও দিবা',
    type: 'সেনাবাহিনী পরিচালিত',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'চলমান শৃঙ্খলা, চরিত্র গঠন ও চমৎকার বোর্ডের ফলাফলের মাধ্যমে কেন্টনমেন্ট পাবলিক কলেজ চট্টগ্রাম বিভাগের মডেল প্রতিষ্ঠানে পরিণত হয়েছে।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '৫০০',
    seatsCommerce: '২০০',
    seatsArts: '১০০',
    totalSeats: '৮০০',
    description: 'বাংলাদেশ সেনাবাহিনী পরিচালিত ঐতিহ্যবাহী কেন্টনমেন্ট পাবলিক স্কুল অ্যান্ড কলেজ চট্টগ্রাম।',
    address: 'বায়েজিদ বোস্তামী রোড, চট্টগ্রাম কেন্টনমেন্ট – ৪২১০',
    website: 'https://cpscc.edu.bd',
  },
  {
    slug: 'ccpc-chittagong',
    name: 'Chittagong Cantonment Public College',
    bnName: 'চট্টগ্রাম কেন্টনমেন্ট পাবলিক কলেজ (CCPC)',
    eiin: '১০৪২৯০',
    established: '১৯৬১',
    location: 'চট্টগ্রাম কেন্টনমেন্ট',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'প্রভাতী ও দিবা (সহশিক্ষা)',
    type: 'সেনাবাহিনী পরিচালিত',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'বিভাগীয় ও জাতীয় পর্যায়ে উচ্চ মাধ্যমিক পরীক্ষার ভালো ফলাফলে সিসিপিসি সুনাম বজায় রেখে আসছে।',
    scienceGPA: '5.00',
    commerceGPA: '4.60',
    artsGPA: '4.00',
    seatsScience: '৭০০',
    seatsCommerce: '৩৫০',
    seatsArts: '১৫০',
    totalSeats: '১,২০০',
    description: 'চট্টগ্রাম সেনানিবাসে অবস্থিত সিসিপিসি (CCPC) চট্টগ্রামের অন্যতম শীর্ষ পছন্দনীয় কলেজ।',
    address: 'চট্টগ্রাম কেন্টনমেন্ট, চট্টগ্রাম – ৪২১০',
    website: 'https://ccpc.edu.bd',
  },
  {
    slug: 'comilla-victoria-college',
    name: 'Comilla Victoria Government College',
    bnName: 'কুমিল্লা ভিক্টোরিয়া সরকারি কলেজ',
    eiin: '১০৫৮১১',
    established: '১৮৯৯',
    location: 'কান্দিরপাড়, কুমিল্লা',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি ঐতিহ্যবাহী',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: '১৮৯৯ সালে রাণী ভিক্টোরিয়ার স্মরণে প্রতিষ্ঠিত এই ঐতিহ্যবাহী কলেজে আমরা সমৃদ্ধ জ্ঞান চর্চা নিশ্চিত করি।',
    scienceGPA: '5.00',
    commerceGPA: '4.65',
    artsGPA: '4.25',
    seatsScience: '৮০০',
    seatsCommerce: '৪০০',
    seatsArts: '৩০০',
    totalSeats: '১,৫০০',
    description: '১৮৯৯ সালে প্রতিষ্ঠিত বৃহত্তর কুমিল্লার শ্রেষ্ঠ সরকারি ভিক্টোরিয়া কলেজ।',
    address: 'কান্দিরপাড়, কুমিল্লা – ৩৫০০',
    website: 'https://cvgc.edu.bd',
  },
  {
    slug: 'feni-gov-college',
    name: 'Feni Government College',
    bnName: 'ফেনী সরকারি কলেজ',
    eiin: '১০৬৬৫১',
    established: '১৯২২',
    location: 'ফেনী সদর',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'ফেনী জেলার প্রাণকেন্দ্রে অবস্থিত শতবর্ষী ঐতিহ্যবাহী ফেনী সরকারি কলেজ।',
    scienceGPA: '4.85',
    commerceGPA: '4.25',
    artsGPA: '3.75',
    seatsScience: '৬০০',
    seatsCommerce: '৩০০',
    seatsArts: '২০০',
    totalSeats: '১,১০০',
    description: '১৯২২ সালে প্রতিষ্ঠিত ফেনী জেলার সেরা সরকারি কলেজ।',
    address: 'কলেজ রোড, ফেনী – ৩৯০০',
    website: 'https://fenigovcollege.edu.bd',
  },
  {
    slug: 'noakhali-gov-college',
    name: 'Noakhali Government College',
    bnName: 'নোয়াখালী সরকারি কলেজ',
    eiin: '১০৭৫৮৮',
    established: '১৯৬৩',
    location: 'মাইজদী কোর্ট, নোয়াখালী',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'নোয়াখালী জেলার প্রাচীনতম সরকারি উচ্চ মাধ্যমিক বিদ্যাপিঠ।',
    scienceGPA: '4.85',
    commerceGPA: '4.25',
    artsGPA: '3.80',
    seatsScience: '৬০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,২০০',
    description: '১৯৬৩ সালে প্রতিষ্ঠিত নোয়াখালী মাইজদী শহরের ঐতিহ্যবাহী সরকারি কলেজ।',
    address: 'মাইজদী কোর্ট, নোয়াখালী – ৩৮০০',
    website: 'https://ngc.edu.bd',
  },
  {
    slug: 'coxsbazar-gov-college',
    name: 'Cox\'s Bazar Government College',
    bnName: 'কক্সবাজার সরকারি কলেজ',
    eiin: '১০৬২০০',
    established: '১৯৬২',
    location: 'লিংক রোড, কক্সবাজার',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'পর্যটন নগরী কক্সবাজারের প্রধানতম শিক্ষা নিকেতন কক্সবাজার সরকারি কলেজ।',
    scienceGPA: '4.75',
    commerceGPA: '4.00',
    artsGPA: '3.50',
    seatsScience: '৫০০',
    seatsCommerce: '৩০০',
    seatsArts: '২০০',
    totalSeats: '১,০০০',
    description: '১৯৬২ সালে প্রতিষ্ঠিত কক্সবাজার জেলার সেরা ঐতিহ্যবাহী সরকারি উচ্চ মাধ্যমিক কলেজ।',
    address: 'লিংক রোড, কক্সবাজার – ৪৭০০',
    website: 'https://cbgc.edu.bd',
  },
  {
    slug: 'chandpur-gov-college',
    name: 'Chandpur Government College',
    bnName: 'চাঁদপুর সরকারি কলেজ',
    eiin: '১০৩৫৮৭',
    established: '১৯৪৬',
    location: 'স্টেডিয়াম রোড, চাঁদপুর',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: '১৯৪৬ সালে প্রতিষ্ঠিত ইলিশের বাড়ি চাঁদপুর জেলার শ্রেষ্ঠ সরকারি বিদ্যাপিঠ।',
    scienceGPA: '4.75',
    commerceGPA: '4.00',
    artsGPA: '3.50',
    seatsScience: '৪৫০',
    seatsCommerce: '২৫০',
    seatsArts: '২০০',
    totalSeats: '৯০০',
    description: '১৯৪৬ সালে প্রতিষ্ঠিত চাঁদপুর শহরের প্রাচীন সরকারি কলেজ।',
    address: 'স্টেডিয়াম রোড, চাঁদপুর – ৩৬০০',
    website: 'https://cgc.edu.bd',
  },
  {
    slug: 'patiya-gov-college',
    name: 'Patiya Government College',
    bnName: 'পটিয়া সরকারি কলেজ',
    eiin: '১০৪৮২০',
    established: '১৯৬২',
    location: 'পটিয়া, চট্টগ্রাম',
    division: 'Chattogram Division',
    divisionSlug: 'chattogram-division',
    shift: 'দিবা',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'পটিয়া উপজেলার অন্যতম প্রধান সরকারি বিদ্যাপিঠ।',
    scienceGPA: '4.50',
    commerceGPA: '3.75',
    artsGPA: '3.25',
    seatsScience: '৪০০',
    seatsCommerce: '২৫০',
    seatsArts: '১৫০',
    totalSeats: '৮০০',
    description: '১৯৬২ সালে প্রতিষ্ঠিত পটিয়া উপজেলার বিখ্যাত সরকারি কলেজ।',
    address: 'পটিয়া, চট্টগ্রাম – ৪৩৭০',
    website: 'https://pgc.edu.bd',
  },
  {
    slug: 'rajshahi-college',
    name: 'Rajshahi College',
    bnName: 'রাজশাহী কলেজ',
    eiin: '১২৬৪৯১',
    established: '১৮৭৩',
    location: 'রাজশাহী সদর',
    division: 'Rajshahi Division',
    divisionSlug: 'rajshahi-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'জাতীয় বিশ্ববিদ্যালয়ের র‍্যাংকিংয়ে বারবার দেশের শ্রেষ্ঠ কলেজ নির্বাচিত হওয়া ঐতিহাসিক রাজশাহী কলেজ।',
    scienceGPA: '5.00 (Total Marks 1155+)',
    commerceGPA: '4.75',
    artsGPA: '4.50',
    seatsScience: '৬০০',
    seatsCommerce: '৩০০',
    seatsArts: '২০০',
    totalSeats: '১,১০০',
    description: 'জাতীয় বিশ্ববিদ্যালয়ের র‍্যাংকিংয়ে বারবার দেশের শ্রেষ্ঠ কলেজ নির্বাচিত হওয়া ঐতিহাসিক রাজশাহী কলেজ।',
    address: 'সাহেব বাজার, রাজশাহী – ৬০০০',
    website: 'https://rc.edu.bd',
  },
  {
    slug: 'bl-college',
    name: 'Government BL College Khulna',
    bnName: 'সরকারি বিএল কলেজ খুলনা',
    eiin: '১১৭১৮৬',
    established: '১৯০২',
    location: 'দৌলতপুর, খুলনা',
    division: 'Khulna Division',
    divisionSlug: 'khulna-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'খুলনা বিভাগের ঐতিহ্যবাহী সরকারি ব্রজলাল (বিএল) কলেজ ১৯০২ সালে প্রতিষ্ঠিত হয়।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.00',
    seatsScience: '৬০০',
    seatsCommerce: '৩০০',
    seatsArts: '৩০০',
    totalSeats: '১,২০০',
    description: 'খুলনা বিভাগের ঐতিহ্যবাহী সরকারি ব্রজলাল (বিএল) কলেজ ১৯০২ সালে প্রতিষ্ঠিত হয়।',
    address: 'দৌলতপুর, খুলনা – ৯২০০',
    website: 'https://blcollege.edu.bd',
  },
  {
    slug: 'bm-college',
    name: 'Government BM College Barishal',
    bnName: 'সরকারি ব্রজমোহন (বিএম) কলেজ বরিশাল',
    eiin: '১০০৮৬৬',
    established: '১৮৮৯',
    location: 'বরিশাল সদর',
    division: 'Barishal Division',
    divisionSlug: 'barishal-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: '১৮৮৯ সালে অশ্বিনীকুমার দত্ত প্রতিষ্ঠিত দক্ষিণ বাংলার অক্সফোর্ড খ্যাত বিএম কলেজ।',
    scienceGPA: '4.90',
    commerceGPA: '4.35',
    artsGPA: '4.00',
    seatsScience: '৭০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,৩০০',
    description: 'দক্ষিণবঙ্গের সর্বশ্রেষ্ঠ ঐতিহ্যবাহী সরকারি ব্রজমোহন (বিএম) কলেজ বরিশাল।',
    address: 'বিএম কলেজ রোড, বরিশাল – ৮২০০০',
    website: 'https://bmcollege.edu.bd',
  },
  {
    slug: 'mc-college',
    name: 'Sylhet MC College',
    bnName: 'সিলেট এমসি কলেজ',
    eiin: '১৩০৩০০',
    established: '১৮৯২',
    location: 'টিলাগড়, সিলেট',
    division: 'Sylhet Division',
    divisionSlug: 'sylhet-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: '১৮৯২ সালে প্রতিষ্ঠিত সিলেট বিভাগের শীর্ষতম বিদ্যাপিঠ মুরারীচাঁদ (এমসি) কলেজ।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.25',
    seatsScience: '৬০০',
    seatsCommerce: '৩০০',
    seatsArts: '৩০০',
    totalSeats: '১,২০০',
    description: '১৮৯২ সালে প্রতিষ্ঠিত সিলেট বিভাগের শীর্ষতম বিদ্যাপিঠ মুরারীচাঁদ (এমসি) কলেজ।',
    address: 'টিলাগড়, সিলেট – ৩১০০',
    website: 'https://mccollege.edu.bd',
  },
  {
    slug: 'carmichael-college',
    name: 'Carmichael College Rangpur',
    bnName: 'রংপুর কারমাইকেল কলেজ',
    eiin: '১২৭৪৮০',
    established: '১৯১৬',
    location: 'লালবাগ, রংপুর',
    division: 'Rangpur Division',
    divisionSlug: 'rangpur-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: 'উত্তরাঞ্চলের অক্সফোর্ড খ্যাত ৯০০ একরের ঐতিহাসিক লাল ইটের কারমাইকেল কলেজ রংপুর।',
    scienceGPA: '5.00',
    commerceGPA: '4.50',
    artsGPA: '4.25',
    seatsScience: '৭০০',
    seatsCommerce: '৩৫০',
    seatsArts: '৩৫০',
    totalSeats: '১,৪০০',
    description: 'উত্তরাঞ্চলের অক্সফোর্ড খ্যাত ৯০০ একরের ঐতিহাসিক লাল ইটের কারমাইকেল কলেজ রংপুর।',
    address: 'লালবাগ, রংপুর – ৫৪০০',
    website: 'https://ccr.edu.bd',
  },
  {
    slug: 'ananda-mohan-college',
    name: 'Ananda Mohan College Mymensingh',
    bnName: 'ময়মনসিংহ আনন্দ মোহন কলেজ',
    eiin: '১১১৮৫০',
    established: '১৯০৮',
    location: 'ময়মনসিংহ সদর',
    division: 'Mymensingh Division',
    divisionSlug: 'mymensingh-division',
    shift: 'দিবা (সহশিক্ষা)',
    type: 'সরকারি',
    gender: 'সহশিক্ষা (Co-education)',
    principalMessage: '১৯০৮ সালে আনন্দমোহন বসুর হাত ধরে প্রতিষ্ঠিত ময়মনসিংহ বিভাগের শ্রেষ্ঠ সরকারি কলেজ।',
    scienceGPA: '5.00',
    commerceGPA: '4.60',
    artsGPA: '4.25',
    seatsScience: '৭০০',
    seatsCommerce: '৪০০',
    seatsArts: '২০০',
    totalSeats: '১,৩০০',
    description: '১৯০৮ সালে প্রতিষ্ঠিত ময়মনসিংহ বিভাগের ঐতিহাসিক আনন্দ মোহন কলেজ।',
    address: 'কলেজ রোড, ময়মনসিংহ – ২২০০',
    website: 'https://anandamohan-college.edu.bd',
  },
];
